export default {
    formModalStyles: [
        'flex',
        'justify-center',
        'items-center',
        'fixed',
        'top-0',
        'left-0',
        'w-full',
        'h-screen',
        'bg-black',
        'bg-opacity-60',
        'z-40',
    ].join(' '),
    formElementStyles: [
        'flex',
        'flex-col',
        'gap-6',
        'py-8',
        'px-12',
        'bg-secondary-dark',
        'drop-shadow-sm',
        'rounded-md',
        'w-11/12',
        'max-w-md',
        'animate-slide-from-b',
    ].join(' '),
    formButtonStyles: [
        'bg-primary',
        'hover:bg-primary-dark',
        'py-1',
        'px-4',
        'rounded-full',
        'ease-in-out',
        'duration-100',
        'cursor-pointer w-full',
    ].join(' '),
};
